### ISSUE TITLE
Consider adding "npm run watch" alias

### ISSUE THREAD

**Issue by salcode** [WebDevStudios/wds-block-starter#21]
This project uses `npm run start` to build assets and listen for changes rebuilding the assets on change. In my experience `npm run watch` is a pretty common command for this functionality.

I'd like to see `npm run watch` added as an alias to do the same thing as `npm run start` to ease the process of getting started.

**Comment by gregrickaby** [comment]
Done. https://github.com/WebDevStudios/wds-block-starter/commit/2615bfa3d3b4bb950d73cf7f9d276dbefceea0c9
