### ISSUE TITLE
Different import style in edit.js and save.js

### ISSUE THREAD

**Issue by salcode** [WebDevStudios/wds-block-starter#32]
Currently [edit.js](https://github.com/WebDevStudios/wds-block-starter/blob/master/src/block/rich-text/edit.js#L4) uses the import style

```
import { RichText } from '@wordpress/block-editor';
```

and [save.js](https://github.com/WebDevStudios/wds-block-starter/blob/master/src/block/rich-text/save.js#L4-L8) uses

```
const {
	blockEditor: {
		RichText,
	},
} = wp;
```

If I understand correctly, we could change this to both import from the `wp` global or both from `@wordpress`.

Of course, I recognize there may be a reason for the different styles that I'm not familiar with, however I wanted to bring this up.

**Comment by michealengland** [comment]
@salcode Great catch, I will have a quick fix fired up.

**Comment by salcode** [comment]
@michealengland Am I correct we're better off destructing `wp` rather than using `@wordpress/block-editor`?

**Comment by salcode** [comment]
Now I'm wondering whether we should change this or not.

Based on [packages/block-library/src/html/edit.js](https://github.com/WordPress/gutenberg/blob/f90dc20c331a8f92bd5af1dc6e414acd9ea2779d/packages/block-library/src/html/edit.js#L11) in [WordPress/gutenberg/](https://github.com/WordPress/gutenberg/), I'm trying to add `ToolbarGroup` with

```
const {
  components:
  {
    ToolbarGroup,
  },
} = wp;
```

however `ToobarGroup` does not exist.

I'm guessing this was added to Gutenberg in a release newer than the version currently included in WP Core.

I'm wondering if by going with 

```
```

**Comment by salcode** [comment]
I put together a summary of my thoughts around this in th blog post [WordPress Gutenberg import versus Destructuring Global wp](https://salferrarello.com/wordpress-gutenberg-import-versus-destructuring-global-wp/).

Based on this [related tweet](https://twitter.com/Tarendai/status/1244599833966624768)

> Use import, it's what the official packages use, the official examples, and it has the blessing of the official wp-scripts setup. It might use the other method internally, but that could change in the future. Destructuring a global variable to get dependencies in JSX is weird

I think we should standardize on using `import` not destructing.

**Comment by salcode** [comment]
Note: The conversation in #28 is related and explains why `edit.js` was updated to use `import`.

I think based on all this conversation, the action item coming out of this is to update `save.js` to use `import`.
